[package]
name = "cosmwasm-vault-standard"
version = "0.1.0"
edition = "2021"
authors = ["Sturdy <sturdy@apollo.farm>"]
license = "Apache-2.0"
description = "A standard interface for tokenized vaults written in CosmWasm"
homepage = "https://github.com/apollodao/cosmwasm-vault-standard/"
documentation = "https://docs.rs/cosmwasm-vault-standard"
repository = "https://github.com/apollodao/cosmwasm-vault-standard/"
readme = "README.md"

[features]
default = []
lockup = ["cw-utils"]
force-unlock = []
keeper = []
cw4626 = ["cw20"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
cosmwasm-std = "1.1.0"
schemars = "0.8.8"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
# We must unfourtunately use 1.1.5 since there is a breaking change related to `QueryResponses` macro in 1.1.6
cosmwasm-schema = { version = ">= 1.0.0, <= 1.1.5" }
cw-utils = { version = "0.16.0", optional = true }
cw20 = { version = "0.16.0", optional = true }
