[package]
name = "cosmos-vault-standard"
version = "0.1.0"
edition = "2018"
authors = ["Sturdy <sturdy@apollo.farm>"]

[features]
default = ["cw20s", "lockup"]
lockup = ["cw-utils"]
keeper = []
cw20s = ["cw20", "cw-asset"]

[dependencies]
cosmwasm-std = "1.0.0"
schemars = "0.8.8"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
cw-utils = { version = "^0.13.0", optional = true }
cw20 = { version = "^0.13.0", optional = true }
cw-asset = { version = "^2.3.0", optional = true }
cfg-if = "1.0.0"